apiVersion: v1
kind: Service
metadata:
  name: movies-app-front
spec:
  type: LoadBalancer
  selector:
    app: movies-app-front
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31004
    protocol: TCP